language: cpp
dist: trusty

matrix:
  include:
    #    # Linux C++14 Build
    #    - os: linux
    #      compiler: gcc
    #      env: GCC_VERSION=5 BUILD=Debug STANDARD=14 ASAN=OFF TSAN=OFF
    #      addons:
    #        apt:
    #          sources: ['ubuntu-toolchain-r-test']
    #          packages: [g++-5, valgrind, cmake, cmake-data, ninja-build, lcov]
    #
    #    - os: linux
    #      compiler: gcc
    #      env: GCC_VERSION=5 BUILD=Release STANDARD=14 ASAN=OFF TSAN=OFF
    #      addons:
    #        apt:
    #          sources: ['ubuntu-toolchain-r-test']
    #          packages: [g++-5, valgrind, cmake, cmake-data, ninja-build, lcov]
    #
    #    # Linux C++17 Build
    #    - os: linux
    #      compiler: gcc
    #      env: GCC_VERSION=9 BUILD=Debug STANDARD=17 ASAN=OFF TSAN=OFF
    #      addons:
    #        apt:
    #          sources: ['ubuntu-toolchain-r-test']
    #          packages: [g++-9, valgrind, cmake, cmake-data, ninja-build, lcov]
    #
    #    - os: linux
    #      compiler: gcc
    #      env: GCC_VERSION=9 BUILD=Release STANDARD=17 ASAN=OFF TSAN=OFF
    #      addons:
    #        apt:
    #          sources: ['ubuntu-toolchain-r-test']
    #          packages: [g++-9, valgrind, cmake, cmake-data, ninja-build, lcov]

    # Linux Clang build
    - os: linux
      env: CLANG_VERSION=8 USE_LIB_STDC++=ON BUILD=Debug STANDARD=17 ASAN=OFF TSAN=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-5 # for c++14 libstdc++
            - clang-8
            - valgrind
            - cmake
            - cmake-data
            - ninja-build
            - lcov

    - os: linux
      env: CLANG_VERSION=4 USE_LIB_STDC++=ON BUILD=Debug STANDARD=14 ASAN=OFF TSAN=OFF
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-4 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - g++-5 # for c++14 libstdc++
            - clang-4
            - valgrind
            - cmake
            - cmake-data
            - ninja-build
            - lcov

    # MacOs Clang build
    - os: osx
      env: BUILD=Debug STANDARD=14 ASAN=ON TSAN=OFF
      compiler: clang
      addons:
        homebrew:
          packages:
            - ninja

before_install:
  - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ -n "$CLANG_VERSION" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi

  # For clang also use gcc-5 as we need c++14 libstdc++
  - if [ -n "$USE_LIB_STDC" ]; then sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc; fi
  - if [ -n "$USE_LIB_STDC" ]; then sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++; fi

  # On MacOs use the default system compiler version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXX="clang++" CC="clang"; fi

  - ${CXX} --version
  - cmake --version

install:
  # Get latest gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - sudo tar xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - sudo cmake -GNinja -DBUILD_SHARED_LIBS=ON .
  - sudo cmake --build .
  - sudo cp -r ./googletest/include/gtest /usr/local/include
  - sudo cp ./lib/lib*.so /usr/local/lib

  # Install codecov
  - sudo pip install codecov

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - |
    cmake .. \
      -GNinja \
      -DCMAKE_BUILD_TYPE=$BUILD \
      -DCMAKE_CXX_STANDARD=$STANDARD \
      -DQUILL_SANITIZE_ADDRESS=$ASAN \
      -DQUILL_SANITIZE_THREAD=$TSAN \
      -DQUILL_BUILD_TESTS=ON \
      -DQUILL_BUILD_EXAMPLES=ON
  - cmake --build .
  - ctest --verbose

branches:
  only:
    - master

notifications:
  email: false