language: cpp
dist: trusty

matrix:
  include:
    # Linux C++14 Build
    - os: linux
      compiler: gcc
      env: COMPILER=g++-5 BUILD=Debug STANDARD=14 ASAN=OFF TSAN=OFF
      addons:
        apt:
          update: true
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-5, valgrind]

    - os: linux
      compiler: gcc
      env: COMPILER=g++-5 BUILD=Release STANDARD=14 ASAN=OFF TSAN=OFF
      addons:
        apt:
          update: true
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-5, valgrind]

    # Linux C++17 Build
    - os: linux
      compiler: gcc
      env: COMPILER=g++-9 BUILD=Debug STANDARD=17 ASAN=OFF TSAN=OFF
      addons:
        apt:
          update: true
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-9, valgrind]

    - os: linux
      compiler: gcc
      env: COMPILER=g++-9 BUILD=Release STANDARD=17 ASAN=OFF TSAN=OFF
      addons:
        apt:
          update: true
          sources: ['ubuntu-toolchain-r-test']
          packages: [g++-9, valgrind]

install:
  # Get latest gtest
  - sudo wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - sudo tar xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a ./googletest/include/gtest /usr/include
  - sudo cp -a ./lib/libgtest_main.so lib/libgtest.so /usr/lib/

  # Install codecov
  - sudo pip install codecov

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version
  - cmake --version

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir -p build && cd build
  - |
    cmake .. \
      -DCMAKE_BUILD_TYPE=$BUILD \
      -DCMAKE_CXX_STANDARD=$STANDARD \
      -DQUILL_SANITIZE_ADDRESS=$ASAN \
      -DQUILL_SANITIZE_THREAD=$TSAN \
      -DQUILL_BUILD_TESTS=ON \
      -DQUILL_BUILD_EXAMPLES=ON
  - make VERBOSE=1 -j2
  - ctest --verbose

branches:
  only:
    - master

notifications:
  email: false