name: coverage

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Create Build Environment
      run: |
        sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 800; gcov --version
        sudo -H pip install --upgrade pip; sudo -H pip install codecov --ignore-installed
        cmake -E make_directory ${{runner.workspace}}/build
        
    - name: Configure
      working-directory: ${{runner.workspace}}/build

      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug -DQUILL_CODE_COVERAGE=ON \
              -DCMAKE_CXX_STANDARD=17 -DQUILL_BUILD_TESTS=ON \
              -DQUILL_BUILD_EXAMPLES=ON -DQUILL_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE
               
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --verbose -C Debug

    - name: Collect code coverage
      run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
